### ISSUE TITLE
Question: AngularJS Implicit Client, Silent Renew failing with invalid state when calling processTokenCallbackAsync 

### ISSUE THREAD

**Issue by Condor2708** [IdentityServer/IdentityServer3.Samples#162]
I want to know if someone experimented this issue configuring silent renew uri, 
I am using an angularjs controller as a callback url, my oidc token manager object is craeted once the application is started into a singleton factory caled AuthService.
The processResponseAsync function is throwing  invalid state

Thanks

**Comment by iltera** [comment]
If you use the Angular Way to define and access the TokenManager object, you'll get in trouble very quickly. Try a global js variable for TokenManager, outside the angular scope. You'll have access to that variable as an instance of the TokenManager in all your controllers, services and factories.

Otherwise, if you define TokenManager with a factory or service, everytime you access it, angular will create a new instance of TokenManager and the amount of your silent renew counters increase by one for every access. Which means, you will soon have 2, 3, 5... TokenManager objects counting down for a token renewal. And with every call to the TokenManager, a new TokenManager object with different state and nonce values will be created, and when the time comes for a renewal, the values which were stored in the localstorage (or session storage) the first time, will be overriden by the second, third... The active TokenManager which timesout for the token renewal will always have different nonce and state values, thus you get these errors.
